CREATE TABLE BLOCKCHAIN.IRS_CONTRACT ( CONTRACT_ID VARCHAR , 
	BUYER_ID VARCHAR , SELLER_ID VARCHAR , FIXED_LEG_RATE DECIMAL, FLOATING_RATE_INDEX VARCHAR , 
	FLOATING_RATE_SPREAD DECIMAL , NOTIONAL_AMOUNT DECIMAL,  START_DATE DATE , 
	COUPON_FREQUENCY VARCHAR , MATURITY_DATE DATE , PREV_PAYMENT_DATE DATE, NEXT_PAYMENT_DATE DATE,
	PRIMARY KEY (CONTRACT_ID,BUYER_ID,SELLER_ID)) ;
	
	
CREATE TABLE BLOCKCHAIN.IRS_CONTRACT_PROPOSAL ( PROPOSED_BY VARCHAR, CONTRACT_ID VARCHAR , 
	BUYER_ID VARCHAR , SELLER_ID VARCHAR , FIXED_LEG_RATE DECIMAL, 
	FLOATING_RATE_INDEX VARCHAR , FLOATING_RATE_SPREAD DECIMAL ,  
	NOTIONAL_AMOUNT DECIMAL, START_DATE DATE , COUPON_FREQUENCY VARCHAR , 
	MATURITY_DATE DATE ,STATUS VARCHAR, 
	PRIMARY KEY (PROPOSED_BY,CONTRACT_ID,BUYER_ID,SELLER_ID)) ;
	

CREATE TABLE BLOCKCHAIN.IRS_CONTRACT_FLOWS (
    CONTRACT_ID VARCHAR , BUYER_ID VARCHAR , SELLER_ID VARCHAR , FIXED_LEG_AMOUNT DECIMAL ,
    FLOAT_LEG_AMOUNT DECIMAL , NET_AMOUNT DECIMAL , PAYMENT_DUE_DATE DATE ,
    PAYMENT_REMITTANCE_DATE DATE , PAYMENT_REFERENCE_ID VARCHAR ,
	PRIMARY KEY( CONTRACT_ID, BUYER_ID, SELLER_ID, PAYMENT_DUE_DATE ));

CREATE TABLE BLOCKCHAIN.IRS_INTEREST_RATE ( INDEX_NAME VARCHAR, PERIOD VARCHAR, INTEREST_RATE DECIMAL, 
	VALID_FOR_DATE DATE, PRIMARY KEY(INDEX_NAME, PERIOD, VALID_FOR_DATE));
	