version: '3'
services:
  node1:
    image: thetachain/alpha:latest
    environment:
     - IS_FIRST_NODE=true
     - NODE_NAME=node1
     - DEBUG_CONTRACTS=true
    ports:
     - "5520:5520"
     - "5521:5521"
     - "5522:5522"
    volumes:
     - ./data/node1:/usr/local/thetachain/env
     - ../target/classes:/usr/local/thetachain/env/debug_modules/com.gontusoftware.demos
  node2:
    image: thetachain/alpha:latest
    environment:
     - CONNECT_TO_NODE=true
     - CLUSTER_ADDR=node1:5521
     - NODE_NAME=node2
     - DEBUG_CONTRACTS=true
    ports:
     - "4420:5520"
     - "4421:5521"
     - "4422:5522"
    volumes:
     - ./data/node2:/usr/local/thetachain/env
     - ../target/classes:/usr/local/thetachain/env/debug_modules/com.gontusoftware.demos
    links:
    - node1
  reuters:
    image: thetachain/alpha:latest
    environment:
     - CONNECT_TO_NODE=true
     - CLUSTER_ADDR=node1:5521
     - NODE_NAME=Reuters
     - DEBUG_CONTRACTS=true
    ports:
     - "3320:5520"
     - "3321:5521"
     - "3322:5522"
    volumes:
     - ./data/node3:/usr/local/thetachain/env
     - ../target/classes:/usr/local/thetachain/env/debug_modules/com.gontusoftware.demos
    links:
    - node1
